Library('quickfix', [
    'lib/quickfix/DataDictionary.cpp',
    'lib/quickfix/FieldMap.cpp',
    'lib/quickfix/FieldTypes.cpp',
    'lib/quickfix/Group.cpp',
    'lib/quickfix/LIBXML_DOMDocument.cpp',
    'lib/quickfix/Message.cpp',
    'lib/quickfix/MessageSorters.cpp',
    'lib/quickfix/Utility.cpp',
    ],
    CCFLAGS = ['-O2', '-g'],
    CPPPATH = ['gen/quickfix', 'lib/quickfix', '/usr/include/libxml2'])

Program('test1', 'test/test1.cpp',
    CCFLAGS = ['-O2', '-g'],
    CPPPATH = ['lib', 'gen', 'gen/quickfix', 'lib/quickfix'],
    LIBS=['quickfix', 'xml2', 'pthread'],
    LIBPATH='.') 

Program('bench1', 'test/bench.cpp',
    CCFLAGS = ['-O2', '-g'],
    CPPPATH = ['lib', 'gen', 'gen/quickfix', 'lib/quickfix'],
    LIBS=['quickfix', 'xml2', 'pthread'],
    LIBPATH='.')

